#!/bin/bash

echo "🚀 AI Tutor Learning Platform - Git Setup"
echo "=========================================="
echo ""
echo "✅ Local git repository initialized and committed"
echo ""
echo "📋 Next steps to push to remote:"
echo ""
echo "1. Create a new repository on GitHub/GitLab:"
echo "   - Go to https://github.com/new"
echo "   - Name: ai-tutor-learning-platform"
echo "   - Description: AI-powered learning platform with interactive tasks"
echo "   - Make it public or private as preferred"
echo "   - Don't initialize with README (we already have one)"
echo ""
echo "2. After creating the repository, run these commands:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/ai-tutor-learning-platform.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Or if you want to use SSH:"
echo "   git remote add origin git@github.com:YOUR_USERNAME/ai-tutor-learning-platform.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "📁 Current repository status:"
git status --short
echo ""
echo "📊 Repository info:"
echo "   - Total files: $(git ls-files | wc -l)"
echo "   - Commit hash: $(git rev-parse HEAD)"
echo "   - Branch: $(git branch --show-current)" 